### ISSUE TITLE
logbooks

### ISSUE THREAD

**Issue by Seerden** [Seerden/track#143]
# Logbooks

logbooks are another way to track things.

A logbook has a template. From this template, users can create entries. Think of a weightlifting logbook. Each logbook entry covers one session. One session can contain any number of exercises or lifts.

A template contains the building blocks for an entry (session). To continue with the example of weightlifting:

template:

- lift(s)
- notes

From these building blocks (template "items"), a user can build a session template. A session has one section for notes,, and a user can add as many lifts as they want.

Each template item can contain any number of fields. A field can have a number of types. A type can be accompanied by a dimensional unit, or it can be dimension less. A note is just a text (Markdown) field, so it doesn't need dimensionality, but a lift will probably have a sets/reps field of type number with unit "sets" and/or "reps", and a weight field with dimensional unit "kg".

With the template built, the users can start creating logbook entries. A template item can be singular or be specified as a list, which can be added multiple times per entry. Like a squat "lift" entry and a bench press "lift" entry.

Using the collection of a logbook's entries, we can present various statistics, like weight progress on a single lift. Number fields can obviously be presented analytically with various levels of complexity, and we can figure out ways to present dimensionless data too.

---

### Data structure

Because of the genericity and modularity of a logbook, its entries and their items, we need to make sure we get this right from the start.

Currently, my thinking is as follows:
A logbook contains any number of logs. Each log represents a larger entry in the notebook. Logs contain sections that are derived from the log's template. Each section can contain one or multiple items, which are in turn each derived from an item template. An item, through its template, contains any number of fields. Fields can be dimensionless, or they can have a unit. Right now,

I think starting with dimensionless (text) and dimensional (number) fields is good enough, but expanding into more specific field types could be a good idea too. Think of times, duration, etc. Instead of generically interpreting numbers, that would allow for more targeted analysis.

A single item can have multiple entries (rows) in a single log, so we group field values by row, and group all the rows into a single log (entry).

### UI

To start with, do not associate any UI properties with items or fields, except the order of fields inside of an item template.

For the UI, everything is stacked horizontally or vertically, whichever feels best during development of the first version of this feature. Eventually, we can expand the feature so that the user has more control over the visual layout of a logbook and its sections.

## Roadmap

- [X] database tables (#144)
- [ ] types:
  - [X] types that match database tables (#144)
  - [ ] usable types for database interaction (`*Input` types for updating, `New*` types for inserting (#153, \[more?\])
  - [ ] joined types to present to the frontend (like `*WithIds*`, `*WithEntries*`)
- [ ] database interaction functions
  - start thinking about which things we want to join on what for which UI feature
  - [X] query (#153)
  - [ ] update
  - [X] delete (#153)
- [ ] endpoints for database interaction functions (#153?, \[more?\])
- [ ] client-side query hooks to call the endpoints
- [ ] UI for logbook creation and editing
- [ ] UI for log template creation and editing
  - should template changes cascade down to entries? do we disallow breaking template changes?
- [ ] UI for log entry creation and editing
- [ ] UI to present logbooks
- [ ] UI to present logs inside logbook
- [ ] UI to present logbooks to the user other than the logbooks feature home itself

**Comment by Seerden** [comment]
Status: making progress on the initial UI, but there's a lot of hidden complexity in implementation details for this feature, so it's taking longer than I initially challenged myself to spend in this first version.
