### ISSUE TITLE
`Logbooks`: styling

### ISSUE THREAD

**Issue by Seerden** [Seerden/track#193]
Just look at the current state of this component:
Take all components implemented in logbooks v0 into consideration for this issue, not just the actual `Logbooks.tsx` component.

<img src="https://uploads.linear.app/e8d0115d-f3a9-48ca-8a09-c705b4aedc98/d04caee0-ece5-486b-bf03-0dc6459234f1/a5e3d8a3-032d-4cc5-8332-19f86717ff6e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4ZDAxMTVkLWYzYTktNDhjYS04YTA5LWM3MDViNGFlZGM5OC9kMDRjYWVlMC1lY2U1LTQ4NmItYmYwMy0wZGM2NDU5MjM0ZjEvYTVlM2Q4YTMtMDMyZC00Y2M1LTgzMzItMTlmODY3MTdmZjZlIiwiaWF0IjoxNzM0NTMzNTg2LCJleHAiOjMzMzA1MDkzNTg2fQ.KOpWoMmpQ6lxoClPPJP3G0krQpEHlxIT4tALkb5I-Wk " alt="image.png" width="846" />

# Description

- [X] "new logbook" should still be a link, but should look like button with an icon. It should also be in an action bar. I want the action bar to be in line (justified to the right) with the component's title ("Logbooks")
- [X] better empty state (if data was fetched, but user has no logbooks)
- [X] logbook cards: restyle them, and make them all the same size
- [X] add a gap between the cards
- [X] "open details" is ugly
- [X] the button to add a new log is ugly, too
- [X] "open logbook" should be an action button link
- [X] make the description look nicer
- [X] only show log expand icon when hovering, or focus is within, the MiniLog

## Todo (note to self)

- [X] in this PR, I add some LinkButton styled components (in Logbooks.style, LogbookCard.style and a minimal variant in MiniLog.style. Combine these into one shared styled component. Also put the `as={Link}`in the `defaultProps`.
- [ ] Similarly, I implemented a couple Actions/ActionBar styled components. These should probably become responsive too. For the action bar, I think we want to generalize it further into a full-fledged component, because I'm leaning towards wanting to render those differently on smaller viewports.  <br>^ see [TRK-157](https://linear.app/seerden/issue/TRK-157/shared-action-bar-component).
